sudo: false

language: node_js

node_js:
  - 14.5.0

install:
  - yarn

script:
  - yarn test

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: 'cf511f11f76a3a28c067a8107e3bad50b261ad30'
  app: hacker-news-ssr2