sudo: false

language: node_js

node_js:
  - 14.5.0

install:
  - yarn

script:
  - yarn test

notifications:
  email: false

deploy:
  provider: heroku
  username: USERNAME
  password: USERPASSWORD
  app: hacker-news-ssr2
  on:
    repo: devendra-gh/hacker-news-ssr
